### ISSUE TITLE
mobular machinery integration

### ISSUE THREAD

**Issue by lag42** [Pyrofab/Gaspunk#1]
on the modoff server i accidentally killed a mechanical squid with poison gas, then i realized automatons don't need to breathe therefore they should be immune to gas

**Comment by Pyrofab** [comment]
They can fix that themselves, just need to make them actually not breath (not loose air underwater, like iron golems)

**Comment by lag42** [comment]
Do you mean not losing air at all underwater or just immune to drowning damage

**Comment by Pyrofab** [comment]
https://github.com/Pyrofab/Gaspunk/wiki/Custom-gas-behaviour-for-your-entities

**Comment by EPIICTHUNDERCAT** [comment]
r00d!!! JK <3 will add this :) makes sense too
