### ISSUE TITLE
Ability to configure gas clouds lifespan and radius

### ISSUE THREAD

**Issue by Pyrofab** [Pyrofab/Gaspunk#10]
Currently, every aspect of gases can be configured, but there is still no way to configure lifespan of certain gas clouds, or their radius. Such a configuration would be very useful for balancing gas effects.

**Comment by sschr15** [comment]
got it,























assign me

**Comment by sschr15** [comment]
Lifespan done, now will think about adding radius config...

**Comment by sschr15** [comment]
all done
