### ISSUE TITLE
Conflict with Immersive Engineering

### ISSUE THREAD

**Issue by cybercat5555** [Pyrofab/Gaspunk#9]
Immersive Engineering .84
Gaspunk 1.4.5
Forge .2732

Crash: https://pastebin.com/8u3BR4Qi

Upon loading the game, it crashes around the post-initiation stage, dealing with ItemStacks. Uninstalling either Gaspunk or Immersive Engineering fixes the crash

**Comment by Pyrofab** [comment]
Looks like it is mostly on the side of Immersive Engineering, but I will investigate further.

**Comment by cybercat5555** [comment]
I've asked Blu about this as well, and he mentioned Gaspunk may be shipping an outdated version of the IE api

**Comment by Pyrofab** [comment]
Not the cause, but it is fixed in Gaspunk 1.4.6 anyway (pending curse approval)
